name: Main

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose build

      - name: Save image as archive
        run: |
          docker save backend -o backend.tar
          tar -czvf backend.tar.gz backend.tar compose.yaml

      - name: Checkout archive
        run: ls -lh backend.tar.gz

      - name: Set archive permissions
        run: chmod 644 backend.tar.gz

      - name: Replace archive on the VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_KEY }}
          source: backend.tar.gz
          target: ${{ secrets.APP_HOME }}

      - name: Deploy on the VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_KEY }}
          script: |
            cd ${{ secrets.APP_HOME }}
            tar -xzvf backend.tar.gz
            
            export TG_ADMIN_CHAT_ID=${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
            export TG_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            export DB_VOLUME_SOURCE="${{ secrets.APP_HOME }}/volume"
            export BACKEND_WORKING_DIR=/usr/app/back
            export DB_VOLUME_TARGET="${BACKEND_WORKING_DIR}/volume"
            export DB_PATH="${DB_VOLUME_TARGET}/temporarily.db"
            
            if test $(docker ps -q -f name=backend) 
              then
                docker stop backend
            fi
            
            if test $(docker ps -a -q -f name=backend)
              then
                docker rm backend
            fi
            
            if test $(docker images backend)
              then
                docker rmi backend      
            fi

            docker load -i backend.tar
            docker compose up -d          