image_name: $image_name backend
tgz: $tgz tgz_backend

name: Main

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose build

      - name: Save image as archive
        run: docker save *image_name -o *tgz

      - name: Checkout archive
        run: ls -lh *tgz

      - name: Set archive permissions
        run: chmod 644 *tgz

      - name: Replace archive on the VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_KEY }}
          source: tgz_backend
          target: ${{ secrets.APP_HOME }}

      - name: Deploy on the VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_KEY }}
          script: |
            docker load -i ${{ secrets.APP_HOME }}/*tgz
            
            echo ${{ secrets.APP_HOME }}
            
            export BACKEND_WORKING_DIR=${{ secrets.APP_HOME }}
            export BACKEND_ON_PORT=${{ secrets.APP_PORT }}
            export TG_ADMIN_CHAT_ID=${{ secrets.ADMIN_TELEGRAM_CHAT_ID }}
            export TG_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            export DB_PATH="${BACKEND_WORKING_DIR}/volume/temporarily.db"
            export DB_VOLUME_SOURCE=/home/leha/Projects/docker-compose/volume
            export DB_VOLUME_TARGET="${BACKEND_WORKING_DIR}/volume"
            
            if test $(docker ps -q -f name=backend) 
              then
                docker stop backend
            fi
            
            if test $(docker ps -a -q -f name=backend)
              then
                docker rm backend
            fi
            
            if ! test $(docker images -q sln-backend)
              then
                docker compose build
            fi
            
            if test $(docker images -q sln-backend)
              then
                docker compose up -d
              else
                echo "Something went wrong"
            fi